services:
  - type: web
    name: gemma-telegram-bot
    env: python
    region: frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: HF_TOKEN
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
    # Явное указание версии Python
    plan: free